Renamed trusted collaborators to the standardised trusted committer
InnerSourceCommons/InnerSourcePatterns pull request #110
Opened 2019-03-08 19:54 UTC by StingRayZA

The community has standardised the terminology and definition of [Trusted Committer](project-roles/trusted-committer.md). As such, we should probably use the same nomenclature within our own repositories.

(Excuse the multiple commits - there was a rebase in the middle :/ )

2019-03-08 20:23 UTC, rrrutledge requested changes
Great find, @StingRayZA!  Just one small suggestion.

2019-03-08 20:23 UTC, rrrutledge commented on meta/trusted-committers.md
> +There are currently a handful of Github Admins for this repository. They hold the ability to add Committers and modify the repositories nuclear options (delete, rename, etc).
```suggestion
There are currently a handful of Github Admins for this repository. They hold the ability to add collaborators and modify the repositories nuclear options (delete, rename, etc).
```

2019-03-08 20:23 UTC, rrrutledge commented on meta/trusted-committers.md
> +There are currently a handful of Github Admins for this repository. They hold the ability to add Committers and modify the repositories nuclear options (delete, rename, etc).
In this case the sentence refers to the _GitHub_ definition of `collaborator`, so I think it makes sense to leave it.

2019-03-09 00:19 UTC, rrrutledge approved these changes
Awesome.

2019-03-11 11:29 UTC, lenucksi commented
Very nice indeed! Time to press the big green button I say!

2019-03-11 11:29 UTC, merged