Update mindmap to match patterns in the ebook
InnerSourceCommons/InnerSourcePatterns pull request #233
Opened 2020-11-12 11:50 UTC by fwan2000

2020-11-13 20:10 UTC, spier requested changes
@fwan2000 suggested a minor change. Otherwise looks awesome!

2020-11-13 20:10 UTC, spier commented on pattern-categorization/innersource-program-mind-map.md
> +##### [Maturity model](https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/master/patterns/2-structured/maturity-model.md)
```suggestion
##### [Maturity Model](https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/master/patterns/2-structured/maturity-model.md)
```

2020-11-13 20:10 UTC, spier commented
Adding the example of the mindmap rendered as an image, so that everybody knows what this will look like

<img width="1385" alt="innersource-program-mind-map" src="https://user-images.githubusercontent.com/163029/99116659-b131a200-25f4-11eb-9c91-3fe0bf4ad932.png">

2020-11-21 20:48 UTC, spier commented on pattern-categorization/innersource-program-mind-map.md
>  #### radical change of management
```suggestion
#### Radical change of management
```

2020-11-21 20:48 UTC, spier commented on pattern-categorization/innersource-program-mind-map.md
>  #### not enough maintainers to scale
```suggestion
#### Not enough maintainers to scale
```

2020-11-21 20:50 UTC, spier commented on pattern-categorization/innersource-program-mind-map.md
> +### Project setup
```suggestion
### Project Setup
```

2020-11-21 20:50 UTC, spier commented on pattern-categorization/innersource-program-mind-map.md
>  ### Discovery challenges
```suggestion
### Discovery Challenges
```

2020-11-21 20:50 UTC, spier commented on pattern-categorization/innersource-program-mind-map.md
> +### Self education/improvement challenges
```suggestion
### Self Education/Improvement Challenges
```

2020-11-21 20:51 UTC, spier commented on pattern-categorization/innersource-program-mind-map.md
> +#### concern on legal liabilities or cross-company accounting
```suggestion
#### Concern on legal liabilities or cross-company accounting
```

2020-11-21 20:55 UTC, spier commented
@fwan2000 I left a couple of [inline suggestions](https://github.com/InnerSourceCommons/InnerSourcePatterns/pull/233/files), all about changing the capitalization on some of the categories and sentences so that they look more consistent. Looking forward for your review :)

2020-11-22 13:50 UTC, fwan2000 commented
> @fwan2000 I left a couple of [inline suggestions](https://github.com/InnerSourceCommons/InnerSourcePatterns/pull/233/files), all about changing the capitalization on some of the categories and sentences so that they look more consistent. Looking forward for your review :)

Thanks for the suggestions @spier ! I've committed them.

2020-11-23 08:45 UTC, spier approved these changes
LGTM

2020-11-27 21:07 UTC, lenucksi commented
> 
> 
> LGTM

Thanks. That's what I was waiting for.

2020-11-27 21:07 UTC, merged