Initial patter to propose a new source code inventory pattern
InnerSourceCommons/InnerSourcePatterns pull request #322
Opened 2021-04-16 14:18 UTC by dterol23

The proposal follows the pattern template and addresses #310 issue. This is the first time we contribute to the repository so we'll be more than happy to get feature and comments to improve the contribution. Thanks.

2021-04-16 17:13 UTC, spier commented
@dterol23 thank you for putting this together! At a first glance it looks awesome already 🎉 

I will aim to read it through more carefully and leave comments in this PR.

Thank you already for putting in the work and sharing this with the InnerSource community!

2021-04-17 19:53 UTC, spier requested changes
Great first version already @dterol23!

I left a couple of review comments and suggestions inline.

Besides those, some general comments:
- Would it make sense to spell out any possible relationship between your pattern and other existing patterns? For example the [InnerSource Portal](https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/master/patterns/2-structured/innersource-portal.md)?
- Are there any screenshots or mocks that you can use from the inventory in use at Philips?

I hope you find the rest of the feedback useful as well.

And thanks again for sharing this topic with all of us!

2021-04-17 19:53 UTC, spier commented on patterns/1-initial/source-code-inventory.md
> +Enterprise level source code inventory to drive business value and catalyze InnerSource
I would suggest to use shorter name here, so that it becomes easier to reference the pattern by name from elsewhere. For examples of existing pattern names see [this overview](https://github.com/InnerSourceCommons/InnerSourcePatterns#list-of-patterns).

Ideas for alternative titles:

* Unified source code inventory

2021-04-17 19:53 UTC, spier commented on patterns/1-initial/source-code-inventory.md
> +* Fragmentation of source code hosting systems in your organization.
In [another pattern](https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/master/patterns/2-structured/innersource-license.md#glossary) we have introduced these definitions:

**organization** - An umbrella for multiple legal entities. (synonyms: group, enterprise) (e.g. Lufthansa)
**legal entity** - An entity that has its own legal rights and obligations (synonyms: company, subsidiary) (e.g. Lufthansa Systems GmbH, Lufthansa Industry Solutions TS GmbH, ...)

Do you think we could use those in your pattern as well, to stay consistent?

I think we would have to do the following renaming in your pattern:
* organization => legal entity
* enterprise => organization

2021-04-17 19:53 UTC, spier commented on patterns/1-initial/source-code-inventory.md
> +It creates a dynamic and extendable single source of truth for repositories to capture, visualize and act on source code repositories across your organization. That helps to create awareness and focu
Is the "source code maturity framework" here something else than the "source code strategy framework" mentioned above? Or a different name for the same thing?

Also in [the link above](https://github.com/trieshard/source-strategy-assessment/blob/master/framework.md) it is called "Source Code Strategy Assessment Framework", which might be another variant of the same thing? :)

If it is indeed all the same, I would use the exact same name in all the 3 places.

2021-04-17 19:53 UTC, spier commented on patterns/1-initial/source-code-inventory.md
> +* Some InnerSource stakeholders do not value source code at the same level of other Enterprise assets.
Any idea why stakeholders don't value source code the same way?

2021-04-17 19:53 UTC, spier commented on patterns/1-initial/source-code-inventory.md
> +* InnerSource Program wants to support the right projects among all the potential candidates.
```suggestion
* The InnerSource Program wants to support the right projects among all the potential candidates.
```

What qualifies "right projects" here? 
Also why does the InnerSource Program want to do that? i.e. what is their motivation?

2021-04-17 19:53 UTC, spier commented on patterns/1-initial/source-code-inventory.md
> +## Forces
Which of these forces does the source code inventory improve, or improve the most?

2021-04-17 19:53 UTC, spier commented on patterns/1-initial/source-code-inventory.md
> +### Set up an Enterprise level live source code inventory
What do you mean by "live" here?

2021-04-17 19:53 UTC, spier commented on patterns/1-initial/source-code-inventory.md
> +* Combination of manual and automated input data sources to a single source of truth including an API for custom extension
What do you mean by "including an API for custom extension"?
Maybe this should be a dedicated bullet in the Solution?

2021-04-17 19:53 UTC, spier commented on patterns/1-initial/source-code-inventory.md
> +## Problem
I would recommend not to use bullet points here but rather prose.

Also if you can tell a story here about a situation in which you encountered this issue, that would be great too. I know it can be tricky for company's to talk about things like this but the more relatable this Problem section is, the easier for others to identify with it.

2021-04-17 19:53 UTC, spier commented on patterns/1-initial/source-code-inventory.md
> +* We know the ratios of Open, Inner and Closed Source within the Enterprise so we can steer as needed.
```suggestion
* We know the ratios of Open Source, InnerSource and Closed Source within the Enterprise so we can steer as needed.
```

By spelling out these terms I find it easier to read.

2021-04-17 19:53 UTC, spier commented on patterns/1-initial/source-code-inventory.md
> +* We can create awareness and culture shift on certain organizations as needed (e.g., ratio of Open and InnerSource below average)
```suggestion
* We can create awareness and culture shift on certain organizations as needed (e.g., ratio of Open Source and InnerSource below average)
```

2021-04-17 19:53 UTC, spier commented on patterns/1-initial/source-code-inventory.md
> +Enterprises sometimes may manage software, in particular source code as key company asset, with less rigorousness than other IT hardware inventories which may diminish the opportunities to maximize b
What do you mean by "liability costs" in this context?

Also the Patlet would be stronger if we reduce the conjunctive forms (these forms are sometimes referred to as "timid writers voice").

Here a draft of an alternative version
(not that I already used the terms organization and legal entity as explained below):

> In a large organization with multiple legal entities it is often hard to get full transparency into all software assets, in particular all source code, reducing the opportunities to increase business value and control liability costs across the whole organization. An organization-level source code inventory addresses these issues while also exploiting opportunities to identify and support potentially valuable InnerSource assets.

2021-04-17 19:53 UTC, spier commented on patterns/1-initial/source-code-inventory.md
> +* Enable access to automated scanning tools
What do you mean by "scanning tools"?

2021-04-21 09:48 UTC, dterol23 commented on patterns/1-initial/source-code-inventory.md
> +* Fragmentation of source code hosting systems in your organization.
Great. I'll do. Is there any standard way to cross-refer patters? I could not find a dedicated section in the template but it might be good to avoid duplication on term definition for example.

2021-04-21 09:51 UTC, dterol23 commented on patterns/1-initial/source-code-inventory.md
> +It creates a dynamic and extendable single source of truth for repositories to capture, visualize and act on source code repositories across your organization. That helps to create awareness and focu
Thanks. Great comment. Yes. Both the same. I've harmonized the use across the document to avoid confusion.

2021-04-21 09:53 UTC, dterol23 commented on patterns/1-initial/source-code-inventory.md
> +* Some InnerSource stakeholders do not value source code at the same level of other Enterprise assets.
I don't have empirical data or enough sampling. My intuition goes along a general perception around the difficulties of assessing software value for financial capitalization for example. Hardware inventories have an associated value on the balance sheet while software is more intangible.

2021-04-21 11:33 UTC, dterol23 commented on patterns/1-initial/source-code-inventory.md
> +* Enable access to automated scanning tools
I mean static analysis to help on code quality. I clarify further with examples.

2021-04-21 11:36 UTC, dterol23 commented on patterns/1-initial/source-code-inventory.md
> +Enterprises sometimes may manage software, in particular source code as key company asset, with less rigorousness than other IT hardware inventories which may diminish the opportunities to maximize b
Liability cost is often times translated into long, increasing and unpredictable maintenance cost for a given software. In other words, if we don't know what we have we can't plan what it will cost to us. I like your proposal. Let me read it in the context and I'll push a new version.

2021-04-21 13:18 UTC, dterol23 commented on patterns/1-initial/source-code-inventory.md
> +* Fragmentation of source code hosting systems in your organization.
I've finally added in the references section

2021-04-21 13:24 UTC, dterol23 commented on patterns/1-initial/source-code-inventory.md
> +* Fragmentation of source code hosting systems in your organization.
I've finally added as a reference.

2021-04-21 13:41 UTC, dterol23 commented on patterns/1-initial/source-code-inventory.md
> +## Problem
Good feedback. I've rephrased and added few questions to try to capture interest.

2021-04-21 14:05 UTC, dterol23 commented
@spier Thanks for the excellent feedback and guidance you provided. I think I cover it all but please, help to make a second round of review. By the way, I am having difficulties to act on the link check feedback. I think it is related to the new images I've added but I could not figure it out how to solve it. Any idea?

2021-04-21 15:14 UTC, spier commented
@dterol23 you are welcome :) Thanks for producing the next revision.

About the link check:
I think the link check fails because your files have extensions in all uppercase e.g. `assets/img/source-code-inventory-mockup-dashboard.PNG`, but you are referencing the image file in your markdown with a lowercase file extension.

Will take a look at the rest of your changes in the coming days.

2021-04-21 17:53 UTC, dterol23 commented
@spier Good catch on the extension in uppercase. Fixed.

2021-04-21 21:42 UTC, spier commented on patterns/1-initial/source-code-inventory.md
> +- Organization and Legal Entity terms as defined in [InnerSource License Pattern Glossary](https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/master/patterns/2-structured/innersource-lice
```suggestion
- Organization and Legal Entity terms as defined in [InnerSource License Pattern Glossary](../2-structured/innersource-license.md#glossary))
```

Switching to relative links instead.

2021-04-21 21:43 UTC, spier commented on patterns/1-initial/source-code-inventory.md
> +- Explore aligned deployment of this pattern in combination with the [InnerSource Portal pattern](https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/master/patterns/2-structured/innersour
```suggestion
- Explore aligned deployment of this pattern in combination with the [InnerSource Portal pattern](../2-structured/innersource-portal.md).
```

Switching to relative links instead.

2021-04-21 21:46 UTC, spier commented on patterns/1-initial/source-code-inventory.md
> +* Fragmentation of source code hosting systems in your organization.
We don't have a global glossary across all patterns (yet). So what you did is perfect.

As for cross-referencing patterns, what you did works. Sometimes it is also possible to add the references inline somewhere in the pattern itself but either way works.

2021-04-21 21:49 UTC, spier commented on patterns/1-initial/source-code-inventory.md
> +In a large organization with different legal entities is often hard to get full visibility into all software assets, in particular all source code. This situation reduces the opportunities to increas
```suggestion
In a large organization with different legal entities is often hard to get full visibility into all software assets, in particular all source code. This situation reduces the opportunities to increase business value and keep liability costs, such as software maintenance, under control across the organization as a whole. An organization-level source code inventory addresses these issues while exploiting opportunities to identify and support valuable InnerSource assets.
```

2021-04-21 22:05 UTC, spier approved these changes
Great 2nd version!

I have left a couple of more questions for your review.

Normally we would wait with merging until all comment threads on the PR are resolved.

However if you are eager to get this merged, we can also publish this as is an **initial** pattern, and then do further reviews in subsequent PRs if you want. 

Up to you, just let me know.

2021-04-21 22:05 UTC, spier commented on patterns/1-initial/source-code-inventory.md
> +In a large organization with different legal entities is often hard to get full visibility into all software assets, in particular all source code. This situation reduces the opportunities to increas
I believe that this is how it should be spelled. If you agree, then there are a couple of more similar instances in the rest of the doc to fix accordingly.

2021-04-21 22:05 UTC, spier commented on patterns/1-initial/source-code-inventory.md
> +Unified source code inventory
```suggestion
Unified Source Code Inventory
```

Let's go for title-case here, as that's how the other patterns do it.

2021-04-21 22:05 UTC, spier commented on patterns/1-initial/source-code-inventory.md
> +### Set up an Organization level live source code inventory
What do you mean by "live" here?

2021-04-21 22:05 UTC, spier commented on patterns/1-initial/source-code-inventory.md
> +- Explore aligned deployment of this pattern in combination with the [InnerSource Portal pattern](../2-structured/innersource-portal.md).
```suggestion
* Organization and Legal Entity terms as defined in [InnerSource License Pattern Glossary](../2-structured/innersource-license.md#glossary))
* Explore aligned deployment of this pattern in combination with the [InnerSource Portal pattern](../2-structured/innersource-portal.md).
```

Using the same bullet point style as in the rest of the doc.

2021-04-21 22:05 UTC, spier commented on patterns/1-initial/source-code-inventory.md
> +Unified source code inventory
This seems non-controversial. Merging.

2021-04-22 06:21 UTC, dterol23 commented on patterns/1-initial/source-code-inventory.md
> +### Set up an Organization level live source code inventory
I mean a live dashboard. I've updated to make it consistent with the snapshots

2021-04-22 06:25 UTC, dterol23 commented
Thanks @spier I've made a couple of changes to deal with your 2nd round feedback.
Regarding closing the PR, I am fine either way. We use Kanban in our team and I always push to keep small work in progress and close/deliver outstanding stories as soon as possible. But I am also fine waiting for further review if that gets an opportunity to get more feedback soon.

2021-04-22 18:51 UTC, spier commented on patterns/1-initial/source-code-inventory.md
> +* Organization and Legal Entity terms as defined in [InnerSource License Pattern Glossary](../2-structured/innersource-license.md#glossary))
```suggestion
* Organization and Legal Entity terms as defined in [InnerSource License Pattern Glossary](../2-structured/innersource-license.md#glossary)
```

Fixing formatting issue

2021-04-22 18:54 UTC, spier commented on patterns/1-initial/source-code-inventory.md
> +* Explore aligned deployment of this pattern in combination with the [InnerSource Portal pattern](../2-structured/innersource-portal.md).
```suggestion
* Explore using this pattern in combination with the [InnerSource Portal](../2-structured/innersource-portal.md) pattern.
```

Does this simplification of this sentence change the intended meaning?

2021-04-22 18:55 UTC, spier commented on patterns/1-initial/source-code-inventory.md
> +* Example of such a framework: [https://github.com/trieshard/source-strategy-assessment/blob/master/framework.md](https://github.com/trieshard/source-strategy-assessment/blob/master/framework.md)
```suggestion
* Example of such a framework: [github.com/trieshard/source-strategy-assessment/blob/master/framework.md](https://github.com/trieshard/source-strategy-assessment/blob/master/framework.md)
```

2021-04-22 19:00 UTC, spier commented
@dterol23 I love iterations myself! 🎉 

Let's make this the last iteration, and then get this PR merged, so that the pattern shows up in the repo for everybody to see. That may lead to further feedback in the future.

For the last round please see these inline comments here. I think I accidentally filed these outside of a review, which is likely why you didn't see them:
https://github.com/InnerSourceCommons/InnerSourcePatterns/pull/322/files

Feel free to accept/reject and comment on these as you see fit.

Then we get this PR merged in the main line.

2021-04-23 06:09 UTC, dterol23 commented on patterns/1-initial/source-code-inventory.md
> +## Forces
It will improve all of them but root causes will not be removed just with this pattern. It will help to create a wrapper around the fragmentation, it will help teams to define strategies and therefore also contributing to change the culture.

2021-04-23 06:14 UTC, dterol23 commented on patterns/1-initial/source-code-inventory.md
> +* Combination of manual and automated input data sources to a single source of truth including an API for custom extension
What it means is that together with the backend and frontend implementing the inventory dashboard, there must be a way to add new custom data sources so other teams can merge their inputs. In my experience, fragmentation of hosting can be significant so trying to solve everything from the central team will be challenging. I make it a subbullet for better explanation. Please, review.

2021-04-23 06:17 UTC, dterol23 commented
Thanks @spier . I had not seen the other couple of suggestions indeed. I took them into account and make a couple of pushes. Please, take a look. I am good with current version.

2021-04-23 06:35 UTC, spier commented on patterns/1-initial/source-code-inventory.md
> +## Forces
Thanks for the extra context 👍

2021-04-23 06:36 UTC, spier commented
Awesome! Let's get this live!

2021-04-23 06:38 UTC, merged