Add outsourced development ecosystem pattern
InnerSourceCommons/InnerSourcePatterns pull request #662
Opened 2024-03-06 09:49 UTC by dicortazar

This patterns defines an existing problem in large corporations that are highly outsourced.

2024-03-06 15:15 UTC, NewMexicoKid reviewed
Looks like an interesting pattern--thanks for submitting this.

One concern: it appears to focus more on the "how to do it" rather than the "how to win over internal critics and establish management buy-in" even though some of the forces are clearly in the second camp and probably need to be addressed.

2024-03-06 15:15 UTC, NewMexicoKid commented on patterns/1-initial/outsourced-development-ecosystem.md
> +The burdens of existing contracts in an outsourced environment constraints the success of the
constrains

2024-03-06 15:15 UTC, NewMexicoKid commented on patterns/1-initial/outsourced-development-ecosystem.md
> +way to share knowledge, resources, and expertise with competitors within the mother company.
way --> weigh?

... they have to weigh the sharing of knowledge, resources, and expertise with competitors within the mother company.

2024-03-06 15:15 UTC, NewMexicoKid commented on patterns/1-initial/outsourced-development-ecosystem.md
> +InnerSource way. This includes a transparent, collaborative, and community-oriented way.
I would suggest combining the first two sentences:
Current outsourced environments in large corporations prevent those suppliers to work in an InnerSource way, with a greater transparency, collaboration, and sense of community.

2024-03-06 15:15 UTC, NewMexicoKid commented on patterns/1-initial/outsourced-development-ecosystem.md
> +Beyond the implications of the cultural change, and process focus, most of the limitations are
Suggest deleting comma after cultural change

2024-03-06 15:15 UTC, NewMexicoKid commented on patterns/1-initial/outsourced-development-ecosystem.md
> +in a silo-based mode with no interactions with others, but the mother company.
but the mother company --> but only with the mother company.

2024-03-06 15:15 UTC, NewMexicoKid commented on patterns/1-initial/outsourced-development-ecosystem.md
> +* Legal implications and responsibilities when something goes wrong.
I think you need to sharpen this force. What is the behavior change that this force produces?

2024-03-06 15:15 UTC, NewMexicoKid commented on patterns/1-initial/outsourced-development-ecosystem.md
> +* Managers losing control of the situation by having more collaboration across companies borders
Is this Managers fearing the loss of control? Or actual loss of control?

2024-03-06 15:15 UTC, NewMexicoKid commented on patterns/1-initial/outsourced-development-ecosystem.md
> +  * Definition of tools and processes so suppliers do not bring extra complexity to other suppliers.
Is it possible to give an example or mention of how this can be done?

2024-03-06 15:15 UTC, NewMexicoKid commented on patterns/1-initial/outsourced-development-ecosystem.md
> +  even when they are competitors.
Is there, in this solution space, an aspect of a business case that might help drive the adoption of this approach? To fight against the Manager fear of loss of control and the thought that each silo might worry about working with their (internal) competitors?

2024-03-06 15:15 UTC, NewMexicoKid commented on patterns/1-initial/outsourced-development-ecosystem.md
> +  *  Code should be hosted in a collaborative platform every company and contractor is able to reach
Perhaps a semicolon is needed after platform

2024-03-06 15:15 UTC, NewMexicoKid commented on patterns/1-initial/outsourced-development-ecosystem.md
> +* Skill up you suppliers on InnerSource practices
you --> your

2024-03-06 19:30 UTC, spier commented on patterns/1-initial/outsourced-development-ecosystem.md
> +* Skill up you suppliers on InnerSource practices
```suggestion
* Skill up your suppliers on InnerSource practices
```

2024-03-06 19:30 UTC, spier commented on patterns/1-initial/outsourced-development-ecosystem.md
> +The burdens of existing contracts in an outsourced environment constraints the success of the
```suggestion
The burdens of existing contracts in an outsourced environment constrains the success of the
```

2024-03-06 19:32 UTC, spier commented on patterns/1-initial/outsourced-development-ecosystem.md
> +way to share knowledge, resources, and expertise with competitors within the mother company.
Who is the "mother company" in this context?

2024-03-06 19:33 UTC, spier commented on patterns/1-initial/outsourced-development-ecosystem.md
> +The burdens of existing contracts in an outsourced environment constraints the success of the
Fixed

2024-03-06 19:34 UTC, spier commented on patterns/1-initial/outsourced-development-ecosystem.md
> +* Skill up you suppliers on InnerSource practices
fixed

2024-03-08 07:41 UTC, spier commented
I fixed the markdownlint complaints on you PR.

Sorry about all the notification emails that you received. That's just one way for us to try to keep the markdown in our patterns to some standard. Potentially a bit too strict (and with that annoying) at early stages of the content creation process.

2024-03-08 08:04 UTC, spier requested changes
Great start on this new pattern @dicortazar!

The outsourcing topic has been addressed fairly little so far in our patterns, so it is great to get more of this content integrated.

General question:
Is this pattern exclusively about code-level collaboration between two different outsourcing companies? Or is it also between a single outsourcing company and the mother company?

I further recommend to pick fixed terms for the "mother company" and "outsourced company" early on in the pattern, and then stick to it throughout the rest of the pattern.

Again, great work! Hope you find the inline suggestions helpful.

2024-03-08 08:04 UTC, spier commented on patterns/1-initial/outsourced-development-ecosystem.md
> +Current outsourced environments in large corporations prevent those suppliers to work in an
What do you mean by "environments"?

2024-03-08 08:04 UTC, spier commented on patterns/1-initial/outsourced-development-ecosystem.md
> +given by the existing legal framework that forces the outsourced development to charge a fee
Is "legal framework" the same as "contract" here?

2024-03-08 08:04 UTC, spier commented on patterns/1-initial/outsourced-development-ecosystem.md
> +of the code base of this company. Each company or contractor has its own legal contract in place
If there is no difference between "legal contract" and "contract", I would just use the latter.

2024-03-08 08:04 UTC, spier commented on patterns/1-initial/outsourced-development-ecosystem.md
> +## Context
We typically suggest to format the Context as bullet points as well, so that the readers can check one-by-one if this  context also applies at their organization.

2024-03-08 08:04 UTC, spier commented on patterns/1-initial/outsourced-development-ecosystem.md
> +* Legal implications and responsibilities when something goes wrong.
Also what does "something goes wrong" mean?

2024-03-08 08:04 UTC, spier commented on patterns/1-initial/outsourced-development-ecosystem.md
> +* Legal teams and outsourced companies trying to avoid risk exposure and responsibilities.
Is this the legal team at the mother company (the company that is hiring the oursourced company?

Also one general question:
In the English/American context, what is the most common term for "outsourced company"?

Some ideas that come to mind:
- contractors
- agency
- outsourcing partner
- ...

We might also check some of the existing patterns for the terms that we typically use for this.

2024-03-08 08:04 UTC, spier commented on patterns/1-initial/outsourced-development-ecosystem.md
> +  *  Code should be hosted in a collaborative platform every company and contractor is able to reach
I think this was meant as a single sentence, i.e. no semicolon needed :)

Trying to rewrite this:

> Code should be hosted in a collaborative platform (Version Control System) that every company and contractor is able to access and contribute to

We could possibly link to other patterns such as:
- https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/main/patterns/1-initial/source-code-inventory.md
- https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/main/patterns/2-structured/innersource-portal.md (here we should review how this pattern can be adapted, so that it is also usable by contractors)

2024-03-08 08:04 UTC, spier commented on patterns/1-initial/outsourced-development-ecosystem.md
> +  *  State pull request / change request as the by-default way of working and communication.
```suggestion
  *  Define pull requests as the default way of working and communicating (and through that improve async collaboration)
```

2024-03-08 08:04 UTC, spier commented on patterns/1-initial/outsourced-development-ecosystem.md
> +  *  Avoid private developments and releases of tons of lines of code, keep a transparent way of
Can you elaborate on this point?

Are you saying that the contractors should contribute their changes in smaller increments, rather than a big bang?

2024-03-08 08:04 UTC, spier commented on patterns/1-initial/outsourced-development-ecosystem.md
> +* Train the mother company POs to work with several suppliers within the same project.
```suggestion
* Train the Product Owners at the mother company to work with several suppliers within the same project.
```

Train sounds good. But how? What do they have to learn?

2024-03-08 08:04 UTC, spier commented on patterns/1-initial/outsourced-development-ecosystem.md
> +* Define clear and fair guidelines across internal outsourced companies to avoid internal friction.
What do you mean by "internal outsourced companies"?

2024-03-08 08:04 UTC, spier commented on patterns/1-initial/outsourced-development-ecosystem.md
> +* Resources discussions may be part of the conversation at some point, be sure to define the limitations
Can you elaborate on what you mean here?
Might become easier to understand if you break this up into two sentences.

2024-03-21 12:02 UTC, dicortazar commented on patterns/1-initial/outsourced-development-ecosystem.md
> +way to share knowledge, resources, and expertise with competitors within the mother company.
@spier , the mother company would be the company outsourcing services. I am not sure if this is the right word to use, though.

2024-03-21 12:03 UTC, dicortazar commented on patterns/1-initial/outsourced-development-ecosystem.md
> +way to share knowledge, resources, and expertise with competitors within the mother company.
Hi @NewMexicoKid !! Good to see you around :). I wanted to say 'weight' or 'balance' as the company hiring others will need to take care of their outsourced companies so there are not unbalanced situations or frictions.

2024-03-21 12:05 UTC, dicortazar commented on patterns/1-initial/outsourced-development-ecosystem.md
> +Current outsourced environments in large corporations prevent those suppliers to work in an
We can call it context, situation, even ecosystems if you prefer :). The idea behind environment is that this includes many areas of the company, from legal to human resources or engineering teams. And the way outsourced companies are 'forced' to work is sometimes a blocker by itself.

2024-03-21 12:06 UTC, dicortazar commented on patterns/1-initial/outsourced-development-ecosystem.md
> +given by the existing legal framework that forces the outsourced development to charge a fee
Partially. a contract is one very specific document with a very specific outsourced company. The legal framework is the whole process and tools used in the company to start with any new outsourced company onboarding process.

2024-03-23 19:33 UTC, spier commented on patterns/1-initial/outsourced-development-ecosystem.md
> +way to share knowledge, resources, and expertise with competitors within the mother company.
```suggestion
weigh sharing knowledge, resources, and expertise with competitors within the mother company.
```

Changing this to "weigh" and also fixing the grammar.
@NewMexicoKid could you confirm if the grammar would be correct with the fix suggest above?

2024-03-23 19:35 UTC, spier commented on patterns/1-initial/outsourced-development-ecosystem.md
> +Current outsourced environments in large corporations prevent those suppliers to work in an
If we would change this to "outsourced projects" then this would change the meaning of what you are trying to say, right @dicortazar?

2025-09-28 19:39 UTC, spier commented on patterns/1-initial/outsourced-development-ecosystem.md
> +Beyond the implications of the cultural change, and process focus, most of the limitations are
```suggestion
Beyond the implications of the cultural change and process focus, most of the limitations are
```

2025-09-28 19:40 UTC, spier commented on patterns/1-initial/outsourced-development-ecosystem.md
> +of the code base of this company. Each company or contractor has its own legal contract in place
```suggestion
of the code base of this company. Each company or contractor has its own contract in place
```

2025-09-28 19:43 UTC, spier commented on patterns/1-initial/outsourced-development-ecosystem.md
> +in a silo-based mode with no interactions with others, but the mother company.
```suggestion
- Large corporation with a big variety of outsourced companies and contractors that produce part of the code base of this company.
- Each company or contractor has its own contract in place that states the goals, the pricing schema, and the expected outcome and output for the organization.
- No collaboration happens at the outsourced company or contractor level and each of them are working
in a silo-based mode with no interactions with others, but only with the mother company.
```

2025-09-28 19:47 UTC, spier commented on patterns/1-initial/outsourced-development-ecosystem.md
> +* Train the Product Owners at the mother company to work with several suppliers within the same project.
"Train" sounds good. But how? What do they have to learn?

2025-09-28 19:51 UTC, spier commented on patterns/1-initial/outsourced-development-ecosystem.md
> +## Acknowledgments (optional)
```suggestion
## Authors

```

2025-09-28 19:53 UTC, spier commented
@dicortazar thank you again for sharing your experiences with us here.

As this pattern is only in maturity Initial, we should be able to get it merged pretty quickly, which would also make it easier to discover this pattern in our repo.

This PR as staled for some time now, so we are at risk of loosing it entirely.

Do you have time in the comings weeks to review and integrate the review comments?
As you have more than one PR in progress, if you want you can also let me know which one you want to focus on first.

2026-08-01 11:27 UTC, spier commented
I am closing all PRs that are older than 1 year as unmerged.
They are labeled as "stale", and can easily be opened again if the original authors engage again.

To the PR authors:
Please don't take this as disrespect to your original work in any way! We just have tidy up code/issues/PRs every once in a while, to keep the repository and the surrounding community in a healthy and maintainable state. Thank you all!

2026-08-01 11:27 UTC, closed without merging