30 Day Warranty
InnerSourceCommons/InnerSourcePatterns pull request #68
Opened 2017-04-19 14:52 UTC by gruetter

This is the 30 Day Warranty Pattern put in practice by the PayPal folks.

2017-04-21 20:12 UTC, cewilliams requested changes
Generally good, thanks for getting this in! Grammar changes are requested. Context and Forces changes are open for discussion.

2017-04-21 20:12 UTC, cewilliams commented on 30-day-warranty.md
> +Teams depends on another team accepting their contributions so that a component
I think this applies whether the contributing team provides the code or not. The end result that the contributing team is trying to achieve is that the feature is available to them to use, whether they, the receiving team, or another party write the code that provides the feature.

2017-04-21 20:12 UTC, cewilliams commented on 30-day-warranty.md
> +  suspicition that the other team does not know how to write code that would
suspicition -> suspicion

2017-04-21 20:12 UTC, cewilliams commented on 30-day-warranty.md
> +
Additional forces may be:
- Teams fear contributed code will lead to high(er) maintenance costs but do not know how to control for that
- Receiving teams may fear that teaching others how to contribute code will expose technical debt in their system and that visibility may be damaging 
- Receiving teams may not believe that they will get acceptable code no matter how much mentoring they provide
- Either team may not feel confident in measuring risks or certifying that they are mitigated in a contribution

2017-04-21 20:12 UTC, cewilliams commented on 30-day-warranty.md
> +- keeps escalations from becoming to heavyweight
to -> too

2017-04-21 20:12 UTC, cewilliams commented on 30-day-warranty.md
> +- Dirk
Dirk ->  Dirk-Willem van Gulik

2017-08-11 10:08 UTC, gruetter commented
Thanks for the suggestions and changes, @cewilliams ! @psudars : will you have time to review, as well or would you like me to ask around if s.o. else would like to jump in your stead?

2017-08-29 20:12 UTC, NewMexicoKid approved these changes
This has been reviewed by the PLoP 2017 author team and assigned shepherd from PLoP.

2017-08-29 20:12 UTC, NewMexicoKid commented on 30-day-warranty.md
> +   team and
and ...?

2017-08-29 20:14 UTC, merged